package se.citerus.dddsample.domain.model.cargo;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.validation.constraints.NotEmpty;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import se.citerus.dddsample.domain.shared.ValueObject;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 */
@Getter
@Embeddable
@EqualsAndHashCode
public final class TrackingId implements ValueObject<TrackingId> {

    @Column(name = "tracking_id", unique = true, updatable = false)
    @NotEmpty(message = "Tracking ID cannot be empty.")
    private final String id;

    private TrackingId(@NonNull String id) {
        this.id = id;
    }

    public static TrackingId of(String id) {
        return new TrackingId(id);
    }

    @Override
    public boolean sameValueAs(TrackingId other) {
        return other != null && this.id.equals(other.id);
    }

}
